2022-01-24 12:16:51,079 INFO    MainThread:35257 [wandb_setup.py:_flush():71] setting env: {}
2022-01-24 12:16:51,079 INFO    MainThread:35257 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-24 12:16:51,079 INFO    MainThread:35257 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-24 12:16:51,079 INFO    MainThread:35257 [wandb_init.py:_log_setup():371] Logging user logs to /home/pumpkin/.git/CENG-483/hw/hw3/implementation/src/wandb/wandb/run-20220124_121651-3rq8i86h/logs/debug.log
2022-01-24 12:16:51,080 INFO    MainThread:35257 [wandb_init.py:_log_setup():372] Logging internal logs to /home/pumpkin/.git/CENG-483/hw/hw3/implementation/src/wandb/wandb/run-20220124_121651-3rq8i86h/logs/debug-internal.log
2022-01-24 12:16:51,080 INFO    MainThread:35257 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f026d2daa90>
2022-01-24 12:16:51,080 INFO    MainThread:35257 [wandb_init.py:init():404] calling init triggers
2022-01-24 12:16:51,080 INFO    MainThread:35257 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'epochs': 100, 'batch_size': 16, 'learning_rate': 0.001, 'architecture': 'CNN'}
2022-01-24 12:16:51,080 INFO    MainThread:35257 [wandb_init.py:init():424] re-initializing run, found existing run on stack: kmb9ald6
2022-01-24 12:16:51,081 INFO    MainThread:35257 [wandb_run.py:finish():1457] finishing run alpayozkan/vision/kmb9ald6
2022-01-24 12:16:51,081 INFO    MainThread:35257 [jupyter.py:save_history():429] not saving jupyter history
2022-01-24 12:16:51,081 INFO    MainThread:35257 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-24 12:16:51,081 INFO    MainThread:35257 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-24 12:16:51,081 INFO    MainThread:35257 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-24 12:16:51,082 INFO    MainThread:35257 [wandb_run.py:_restore():1752] restore
2022-01-24 12:16:51,760 INFO    MainThread:35257 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 833
  total_bytes: 833
}

2022-01-24 12:16:56,863 INFO    MainThread:35257 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-01-24 12:16:56,963 INFO    MainThread:35257 [wandb_run.py:_restore():1752] restore
2022-01-24 12:16:56,970 ERROR   MainThread:35257 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1971, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1911, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/pumpkin/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
